version: '3.0'

services:

  # MySQL8
  mysql8:
    image: mysql:8.0.29
#    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 设置初始化脚本
      - ./script/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      # 这里映射为了 13306 端口
      - "13306:3306"

  # Redis
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'