apiVersion: v1
# 这个指 k8s 有哪些 volume
kind: PersistentVolume
metadata:
  name: webook-mysql-pv
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    # 只能一个 POD 读写
    - ReadWriteOnce
  hostPath:
    # mysql 的 /var/lib/mysql 映射到 k8s 的 /mnt/mysql
    path: "/mnt/mysql"
