test:
  key: value1234

redis:
  addr: "localhost:16379"

db:
  dsn: "root:root@tcp(localhost:13306)/webook"

kafka:
  addr:
    - "localhost:9094"
# - 表示切片

etcd:
  addrs:
    - "localhost:12379"

grpc:
  client:
    intr:
      addr: "etcd:///service/interactive"
      threshold: 100