// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic-go/webook/relationship/grpc"
	"basic-go/webook/relationship/ioc"
	"basic-go/webook/relationship/repository"
	"basic-go/webook/relationship/repository/cache"
	"basic-go/webook/relationship/repository/dao"
	"basic-go/webook/relationship/service"

	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	followRelationDao := dao.NewGORMFollowRelationDAO(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewFollowRelationRepository(followRelationDao, followCache, loggerV1)
	followRelationService := service.NewFollowRelationService(followRepository)
	followServiceServer := grpc.NewFollowRelationServiceServer(followRelationService)
	server := ioc.InitGrpcxServer(followServiceServer, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMFollowRelationDAO, repository.NewFollowRelationRepository, service.NewFollowRelationService, grpc.NewFollowRelationServiceServer, cache.NewRedisFollowCache)

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitRedis)
